### ISSUE TITLE
Code optimization for adding notes feature

### ISSUE THREAD

**Issue by mohamed26n** [SemirSljiivic/NotizenApp#1]
Description:

The current implementation for adding notes feature could benefit from code optimization. The code works as expected but could be improved in terms of performance and readability.

Some areas of the code that could be optimized include reducing redundant code, improving variable naming, and using more efficient data structures and algorithms.

Optimizing the code will not only improve the overall performance of the application but also make it easier for developers to understand and maintain the code in the future.

I would like to suggest that we work together as a community to optimize the code for adding notes feature. Any suggestions, feedback, or pull requests are welcome. Let's make this feature better together

**Comment by MustafaSataric** [comment]
Thank you for your issue i will consider it in the repository.

**Comment by mohamed26n** [comment]
Thx
